// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/user/user-common.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetUsers
type GetUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_952d84beea577839, []int{0}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

type GetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_952d84beea577839, []int{1}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// ModifyUser
type ModifyUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserRequest) Reset()         { *m = ModifyUserRequest{} }
func (m *ModifyUserRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyUserRequest) ProtoMessage()    {}
func (*ModifyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_952d84beea577839, []int{2}
}

func (m *ModifyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserRequest.Unmarshal(m, b)
}
func (m *ModifyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserRequest.Marshal(b, m, deterministic)
}
func (m *ModifyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserRequest.Merge(m, src)
}
func (m *ModifyUserRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyUserRequest.Size(m)
}
func (m *ModifyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserRequest proto.InternalMessageInfo

func (m *ModifyUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// DeleteUser
type DeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_952d84beea577839, []int{3}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// UserModel ...
type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role                 int32    `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	SshKeys              []string `protobuf:"bytes,5,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_952d84beea577839, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *User) GetSshKeys() []string {
	if m != nil {
		return m.SshKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUsersRequest)(nil), "proto.user.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "proto.user.GetUsersResponse")
	proto.RegisterType((*ModifyUserRequest)(nil), "proto.user.ModifyUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "proto.user.DeleteUserRequest")
	proto.RegisterType((*User)(nil), "proto.user.User")
}

func init() { proto.RegisterFile("proto/v1/user/user-common.proto", fileDescriptor_952d84beea577839) }

var fileDescriptor_952d84beea577839 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x4d, 0xbf, 0xd6, 0x83, 0xed, 0x5e, 0x8c, 0x45, 0x30, 0x84, 0x52, 0x7a, 0x68,
	0xb3, 0xa8, 0x27, 0x3d, 0x8a, 0x20, 0x22, 0x5e, 0x02, 0x5e, 0xbc, 0x94, 0xb4, 0x19, 0xb7, 0xc1,
	0x64, 0x27, 0x66, 0xb6, 0x96, 0x5e, 0xfc, 0xdb, 0x65, 0x27, 0x60, 0x15, 0xf5, 0x32, 0x1f, 0xef,
	0xf7, 0xde, 0xee, 0xc2, 0x8a, 0xb3, 0xaa, 0x46, 0x8b, 0xea, 0xfd, 0x5c, 0x6d, 0x08, 0x6a, 0x2e,
	0xf3, 0x15, 0x96, 0x25, 0x9a, 0x98, 0x89, 0x14, 0xdc, 0x62, 0x07, 0x46, 0xa7, 0x1a, 0x51, 0x17,
	0xa0, 0xd2, 0x2a, 0x57, 0xa9, 0x31, 0x68, 0x53, 0x9b, 0xa3, 0xa1, 0xc6, 0x39, 0x9a, 0x71, 0x5b,
	0xcd, 0x35, 0x98, 0x39, 0x6d, 0x53, 0xad, 0xa1, 0x56, 0x58, 0xb1, 0xe3, 0xb7, 0x3b, 0x1a, 0x8a,
	0xa3, 0x3b, 0xb0, 0x4f, 0x04, 0x35, 0x25, 0xf0, 0xb6, 0x01, 0xb2, 0xd1, 0xb5, 0x18, 0xec, 0x25,
	0xaa, 0xd0, 0x10, 0xc8, 0x89, 0x68, 0xbb, 0xab, 0x29, 0xf0, 0xc2, 0xd6, 0xf4, 0xf0, 0x62, 0x10,
	0xef, 0x9f, 0x13, 0x3b, 0x67, 0xd2, 0xe0, 0xe8, 0x4a, 0x0c, 0x1f, 0x31, 0xcb, 0x5f, 0x76, 0x2c,
	0x36, 0x07, 0xca, 0xb1, 0xf0, 0x1d, 0x0d, 0xbc, 0xd0, 0xfb, 0x33, 0xcb, 0x34, 0x9a, 0x89, 0xe1,
	0x2d, 0x14, 0x60, 0xe1, 0x7b, 0xf4, 0x58, 0x74, 0x1d, 0x5c, 0xe4, 0x19, 0xa7, 0xfb, 0x49, 0xc7,
	0xad, 0xf7, 0x59, 0xf4, 0x21, 0x7c, 0xe7, 0xfb, 0xd7, 0x20, 0x47, 0xa2, 0x57, 0xa5, 0x44, 0x5b,
	0xac, 0xb3, 0xe0, 0x80, 0xc9, 0xd7, 0x2e, 0xa5, 0xf0, 0x4d, 0x5a, 0x42, 0xd0, 0x62, 0x9d, 0x67,
	0xa7, 0xd5, 0x58, 0x40, 0xe0, 0x87, 0xde, 0xb4, 0x9d, 0xf0, 0x2c, 0x4f, 0x44, 0x8f, 0x68, 0xbd,
	0x78, 0x85, 0x1d, 0x05, 0xed, 0xb0, 0x35, 0xed, 0x27, 0x5d, 0xa2, 0xf5, 0x03, 0xec, 0xe8, 0x66,
	0xf2, 0x3c, 0xd6, 0xb9, 0x5d, 0x6f, 0x96, 0xf1, 0x0a, 0x4b, 0xa5, 0xb1, 0x2c, 0xb8, 0x80, 0x55,
	0x3f, 0x7e, 0x72, 0xd9, 0xe1, 0xf5, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xff, 0x89, 0x5b,
	0xe1, 0x01, 0x00, 0x00,
}
