version: '2.3'

services:
  metalica:
    image: '${PRIVATE_REGISTRY}/metalica:${VERSION}'
    build:
      context: .
      dockerfile: ./gomlet/prod.Dockerfile
    runtime: nvidia
    hostname: gomlet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '7777:7777'
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
