// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/goml/gomlet/server"
)

// Injectors from wire.go:

func setup() (*server.Server, func(), error) {
	mainApplication := newApplication()
	serveMux := newRouter(mainApplication)
	defaultDriver := server.NewDefaultDriver()
	gomlapiServer := server.NewGomlapiServer()
	gomletServer := server.NewGomletServer()
	userServer := server.NewUserServer()
	authServer := server.NewAuthServer()
	options := &server.Options{
		Driver:        defaultDriver,
		GomlapiServer: gomlapiServer,
		GomletServer:  gomletServer,
		UserServer:    userServer,
		AuthServer:    authServer,
	}
	serverServer := server.NewServer(serveMux, options)
	return serverServer, func() {
	}, nil
}
