// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/gomlet/gomlet-common.proto

package gomlet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/goml/gomlet/proto/v1/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetNode
type GetNodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{0}
}

func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(m, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

type GetNodeResponse struct {
	Node                 *common.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetNodeResponse) Reset()         { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()    {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{1}
}

func (m *GetNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeResponse.Unmarshal(m, b)
}
func (m *GetNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeResponse.Merge(m, src)
}
func (m *GetNodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeResponse.Size(m)
}
func (m *GetNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeResponse proto.InternalMessageInfo

func (m *GetNodeResponse) GetNode() *common.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

// CreateContainer
type CreateContainerRequest struct {
	ImageName            string            `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ContainerName        string            `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Volumes              map[string]string `protobuf:"bytes,4,rep,name=volumes,proto3" json:"volumes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Envs                 []string          `protobuf:"bytes,5,rep,name=envs,proto3" json:"envs,omitempty"`
	Ports                map[int32]string  `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AutoPort             bool              `protobuf:"varint,9,opt,name=auto_port,json=autoPort,proto3" json:"auto_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateContainerRequest) Reset()         { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()    {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{2}
}

func (m *CreateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerRequest.Unmarshal(m, b)
}
func (m *CreateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerRequest.Marshal(b, m, deterministic)
}
func (m *CreateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerRequest.Merge(m, src)
}
func (m *CreateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContainerRequest.Size(m)
}
func (m *CreateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerRequest proto.InternalMessageInfo

func (m *CreateContainerRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *CreateContainerRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *CreateContainerRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CreateContainerRequest) GetVolumes() map[string]string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *CreateContainerRequest) GetEnvs() []string {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *CreateContainerRequest) GetPorts() map[int32]string {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *CreateContainerRequest) GetAutoPort() bool {
	if m != nil {
		return m.AutoPort
	}
	return false
}

type CreateContainerResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Warnings             []string `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerResponse) Reset()         { *m = CreateContainerResponse{} }
func (m *CreateContainerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContainerResponse) ProtoMessage()    {}
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{3}
}

func (m *CreateContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerResponse.Unmarshal(m, b)
}
func (m *CreateContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerResponse.Marshal(b, m, deterministic)
}
func (m *CreateContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerResponse.Merge(m, src)
}
func (m *CreateContainerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContainerResponse.Size(m)
}
func (m *CreateContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerResponse proto.InternalMessageInfo

func (m *CreateContainerResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateContainerResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

// GetContainers
type GetContainersRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContainersRequest) Reset()         { *m = GetContainersRequest{} }
func (m *GetContainersRequest) String() string { return proto.CompactTextString(m) }
func (*GetContainersRequest) ProtoMessage()    {}
func (*GetContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{4}
}

func (m *GetContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainersRequest.Unmarshal(m, b)
}
func (m *GetContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainersRequest.Marshal(b, m, deterministic)
}
func (m *GetContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainersRequest.Merge(m, src)
}
func (m *GetContainersRequest) XXX_Size() int {
	return xxx_messageInfo_GetContainersRequest.Size(m)
}
func (m *GetContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainersRequest proto.InternalMessageInfo

func (m *GetContainersRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type GetContainersResponse struct {
	Containers           []*common.Container `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetContainersResponse) Reset()         { *m = GetContainersResponse{} }
func (m *GetContainersResponse) String() string { return proto.CompactTextString(m) }
func (*GetContainersResponse) ProtoMessage()    {}
func (*GetContainersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{5}
}

func (m *GetContainersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainersResponse.Unmarshal(m, b)
}
func (m *GetContainersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainersResponse.Marshal(b, m, deterministic)
}
func (m *GetContainersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainersResponse.Merge(m, src)
}
func (m *GetContainersResponse) XXX_Size() int {
	return xxx_messageInfo_GetContainersResponse.Size(m)
}
func (m *GetContainersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainersResponse proto.InternalMessageInfo

func (m *GetContainersResponse) GetContainers() []*common.Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

// StartContainer
type StartContainerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartContainerRequest) Reset()         { *m = StartContainerRequest{} }
func (m *StartContainerRequest) String() string { return proto.CompactTextString(m) }
func (*StartContainerRequest) ProtoMessage()    {}
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{6}
}

func (m *StartContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartContainerRequest.Unmarshal(m, b)
}
func (m *StartContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartContainerRequest.Marshal(b, m, deterministic)
}
func (m *StartContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartContainerRequest.Merge(m, src)
}
func (m *StartContainerRequest) XXX_Size() int {
	return xxx_messageInfo_StartContainerRequest.Size(m)
}
func (m *StartContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartContainerRequest proto.InternalMessageInfo

func (m *StartContainerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// StopContainer
type StopContainerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopContainerRequest) Reset()         { *m = StopContainerRequest{} }
func (m *StopContainerRequest) String() string { return proto.CompactTextString(m) }
func (*StopContainerRequest) ProtoMessage()    {}
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{7}
}

func (m *StopContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopContainerRequest.Unmarshal(m, b)
}
func (m *StopContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopContainerRequest.Marshal(b, m, deterministic)
}
func (m *StopContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopContainerRequest.Merge(m, src)
}
func (m *StopContainerRequest) XXX_Size() int {
	return xxx_messageInfo_StopContainerRequest.Size(m)
}
func (m *StopContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopContainerRequest proto.InternalMessageInfo

func (m *StopContainerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DeleteContainer
type DeleteContainerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContainerRequest) Reset()         { *m = DeleteContainerRequest{} }
func (m *DeleteContainerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContainerRequest) ProtoMessage()    {}
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ba3117f3f6d448, []int{8}
}

func (m *DeleteContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContainerRequest.Unmarshal(m, b)
}
func (m *DeleteContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContainerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContainerRequest.Merge(m, src)
}
func (m *DeleteContainerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContainerRequest.Size(m)
}
func (m *DeleteContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContainerRequest proto.InternalMessageInfo

func (m *DeleteContainerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNodeRequest)(nil), "proto.gomlet.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "proto.gomlet.GetNodeResponse")
	proto.RegisterType((*CreateContainerRequest)(nil), "proto.gomlet.CreateContainerRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.gomlet.CreateContainerRequest.LabelsEntry")
	proto.RegisterMapType((map[int32]string)(nil), "proto.gomlet.CreateContainerRequest.PortsEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.gomlet.CreateContainerRequest.VolumesEntry")
	proto.RegisterType((*CreateContainerResponse)(nil), "proto.gomlet.CreateContainerResponse")
	proto.RegisterType((*GetContainersRequest)(nil), "proto.gomlet.GetContainersRequest")
	proto.RegisterType((*GetContainersResponse)(nil), "proto.gomlet.GetContainersResponse")
	proto.RegisterType((*StartContainerRequest)(nil), "proto.gomlet.StartContainerRequest")
	proto.RegisterType((*StopContainerRequest)(nil), "proto.gomlet.StopContainerRequest")
	proto.RegisterType((*DeleteContainerRequest)(nil), "proto.gomlet.DeleteContainerRequest")
}

func init() {
	proto.RegisterFile("proto/v1/gomlet/gomlet-common.proto", fileDescriptor_14ba3117f3f6d448)
}

var fileDescriptor_14ba3117f3f6d448 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0x7f, 0xd2, 0x5e, 0x47, 0x99, 0xac, 0xae, 0x8b, 0xc2, 0x90, 0xaa, 0x20, 0x4a, 0x1e,
	0x68, 0xc2, 0xc6, 0x03, 0xdb, 0x1e, 0x19, 0xd5, 0x90, 0x40, 0xd3, 0xd4, 0x49, 0x3c, 0xf0, 0x32,
	0xb9, 0xed, 0x11, 0xa2, 0x25, 0x76, 0xb0, 0xdd, 0x4e, 0xfb, 0x67, 0xf8, 0x5b, 0x51, 0x6c, 0x37,
	0x0b, 0xe9, 0xa4, 0x8d, 0x27, 0xfb, 0xee, 0xbe, 0xef, 0x3b, 0xdf, 0xe5, 0x72, 0xf0, 0x3a, 0x13,
	0x5c, 0xf1, 0x70, 0x7d, 0x18, 0x46, 0x3c, 0x4d, 0x50, 0xd9, 0x63, 0xb2, 0xe0, 0x69, 0xca, 0x59,
	0xa0, 0xa3, 0x64, 0x47, 0x1f, 0x81, 0x09, 0xb9, 0x07, 0x05, 0xc5, 0x80, 0xc2, 0x25, 0x5f, 0xdc,
	0xa0, 0x30, 0x58, 0xd7, 0xad, 0x46, 0x19, 0x5f, 0xa2, 0x8d, 0x1d, 0x44, 0x9c, 0x47, 0x09, 0x86,
	0x34, 0x8b, 0x43, 0xca, 0x18, 0x57, 0x54, 0xc5, 0x9c, 0x49, 0x1b, 0x7d, 0xa7, 0x8f, 0xc5, 0x24,
	0x42, 0x36, 0x91, 0xb7, 0x34, 0x8a, 0x50, 0x84, 0x3c, 0xd3, 0x88, 0x6d, 0xb4, 0xb7, 0x0b, 0xfd,
	0x73, 0x54, 0x17, 0x7c, 0x89, 0x33, 0xfc, 0xbd, 0x42, 0xa9, 0xbc, 0x13, 0x78, 0x51, 0x78, 0x64,
	0xc6, 0x99, 0x44, 0x32, 0x86, 0x66, 0x9e, 0xde, 0xa9, 0x8d, 0x6a, 0x7e, 0xef, 0x88, 0x18, 0x6a,
	0x60, 0x6b, 0xd3, 0x48, 0x1d, 0xf7, 0xfe, 0x34, 0x61, 0x78, 0x26, 0x90, 0x2a, 0x3c, 0xe3, 0x4c,
	0xd1, 0x98, 0xa1, 0xb0, 0xaa, 0xe4, 0x15, 0x40, 0x9c, 0xd2, 0x08, 0xaf, 0x19, 0x4d, 0x8d, 0x50,
	0x77, 0xd6, 0xd5, 0x9e, 0x0b, 0x9a, 0x22, 0x79, 0x03, 0xfd, 0xc5, 0x86, 0x62, 0x20, 0x75, 0x0d,
	0x79, 0x5e, 0x78, 0x35, 0xec, 0x0b, 0xb4, 0x13, 0x3a, 0xc7, 0x44, 0x3a, 0x8d, 0x51, 0xc3, 0xef,
	0x1d, 0xbd, 0x0f, 0xca, 0x2d, 0x0d, 0x1e, 0xce, 0x1d, 0x7c, 0xd3, 0x94, 0x29, 0x53, 0xe2, 0x6e,
	0x66, 0xf9, 0xe4, 0x2b, 0x3c, 0x5b, 0xf3, 0x64, 0x95, 0xa2, 0x74, 0x9a, 0x5a, 0xea, 0xf0, 0x49,
	0x52, 0xdf, 0x0d, 0xc7, 0x68, 0x6d, 0x14, 0x08, 0x81, 0x26, 0xb2, 0xb5, 0x74, 0x5a, 0xa3, 0x86,
	0xdf, 0x9d, 0xe9, 0x3b, 0x99, 0x42, 0x2b, 0xe3, 0x42, 0x49, 0xa7, 0xad, 0xe5, 0xc3, 0x27, 0xc9,
	0x5f, 0xe6, 0x0c, 0x23, 0x6e, 0xd8, 0xe4, 0x25, 0x74, 0xe9, 0x4a, 0xf1, 0xeb, 0xdc, 0x72, 0xba,
	0xa3, 0x9a, 0xdf, 0x99, 0x75, 0x72, 0x47, 0x8e, 0x74, 0x4f, 0xa0, 0x57, 0xaa, 0x8d, 0xec, 0x42,
	0xe3, 0x06, 0xef, 0x6c, 0x73, 0xf3, 0x2b, 0x19, 0x40, 0x6b, 0x4d, 0x93, 0xd5, 0xa6, 0x9b, 0xc6,
	0x38, 0xad, 0x1f, 0xd7, 0xdc, 0x53, 0xd8, 0x29, 0xd7, 0xf2, 0x5f, 0xdc, 0x63, 0x80, 0xfb, 0x87,
	0x96, 0x99, 0xad, 0x47, 0x98, 0xde, 0x14, 0xf6, 0xb7, 0x2a, 0xb7, 0x33, 0xd6, 0x87, 0x7a, 0xbc,
	0xb4, 0xf9, 0xeb, 0xf1, 0x92, 0xb8, 0xd0, 0xb9, 0xa5, 0x82, 0xc5, 0x2c, 0x92, 0x4e, 0x5d, 0xf7,
	0xb5, 0xb0, 0xbd, 0x00, 0x06, 0xe7, 0xa8, 0x0a, 0x0d, 0xb9, 0x19, 0xb2, 0x21, 0xb4, 0x7f, 0xc6,
	0x89, 0x42, 0x61, 0x75, 0xac, 0xe5, 0x5d, 0xc2, 0x5e, 0x05, 0x6f, 0x93, 0x7e, 0x04, 0x28, 0x06,
	0x4c, 0x3a, 0x35, 0xfd, 0xa5, 0xf6, 0xff, 0x1d, 0xef, 0xfb, 0x97, 0x96, 0xa0, 0xde, 0x5b, 0xd8,
	0xbb, 0x52, 0x54, 0xa8, 0xad, 0x39, 0xaf, 0x94, 0xe1, 0x8d, 0x61, 0x70, 0xa5, 0x78, 0xf6, 0x28,
	0xce, 0x87, 0xe1, 0x67, 0x4c, 0xf0, 0x81, 0x3f, 0xa7, 0x82, 0xfc, 0xe4, 0xff, 0x18, 0x47, 0xb1,
	0xfa, 0xb5, 0x9a, 0xe7, 0x2f, 0xd4, 0x7b, 0x66, 0xb3, 0x73, 0x2a, 0x3b, 0x68, 0xde, 0xd6, 0x8e,
	0x0f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xed, 0xf7, 0x4b, 0xde, 0x9d, 0x04, 0x00, 0x00,
}
