// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/gomlapi/gomlapi-common.proto

package gomlapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/goml/gomlet/proto/v1/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GomlapiState int32

const (
	GomlapiState_IDLE               GomlapiState = 0
	GomlapiState_INITIALIZING       GomlapiState = 1
	GomlapiState_IMAGE_PULLING      GomlapiState = 2
	GomlapiState_IMAGE_PULLING_FAIL GomlapiState = 3
)

var GomlapiState_name = map[int32]string{
	0: "IDLE",
	1: "INITIALIZING",
	2: "IMAGE_PULLING",
	3: "IMAGE_PULLING_FAIL",
}

var GomlapiState_value = map[string]int32{
	"IDLE":               0,
	"INITIALIZING":       1,
	"IMAGE_PULLING":      2,
	"IMAGE_PULLING_FAIL": 3,
}

func (x GomlapiState) String() string {
	return proto.EnumName(GomlapiState_name, int32(x))
}

func (GomlapiState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{0}
}

// SetConfig
type SetConfigRequest struct {
	Config               *Config  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{0}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

// GetSystem
type GetSystemRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemRequest) Reset()         { *m = GetSystemRequest{} }
func (m *GetSystemRequest) String() string { return proto.CompactTextString(m) }
func (*GetSystemRequest) ProtoMessage()    {}
func (*GetSystemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{1}
}

func (m *GetSystemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemRequest.Unmarshal(m, b)
}
func (m *GetSystemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemRequest.Marshal(b, m, deterministic)
}
func (m *GetSystemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemRequest.Merge(m, src)
}
func (m *GetSystemRequest) XXX_Size() int {
	return xxx_messageInfo_GetSystemRequest.Size(m)
}
func (m *GetSystemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemRequest proto.InternalMessageInfo

type GetSystemResponse struct {
	System               *System  `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemResponse) Reset()         { *m = GetSystemResponse{} }
func (m *GetSystemResponse) String() string { return proto.CompactTextString(m) }
func (*GetSystemResponse) ProtoMessage()    {}
func (*GetSystemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{2}
}

func (m *GetSystemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemResponse.Unmarshal(m, b)
}
func (m *GetSystemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemResponse.Marshal(b, m, deterministic)
}
func (m *GetSystemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemResponse.Merge(m, src)
}
func (m *GetSystemResponse) XXX_Size() int {
	return xxx_messageInfo_GetSystemResponse.Size(m)
}
func (m *GetSystemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemResponse proto.InternalMessageInfo

func (m *GetSystemResponse) GetSystem() *System {
	if m != nil {
		return m.System
	}
	return nil
}

// GetNodeList
type GetNodeListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeListRequest) Reset()         { *m = GetNodeListRequest{} }
func (m *GetNodeListRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeListRequest) ProtoMessage()    {}
func (*GetNodeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{3}
}

func (m *GetNodeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeListRequest.Unmarshal(m, b)
}
func (m *GetNodeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeListRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeListRequest.Merge(m, src)
}
func (m *GetNodeListRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeListRequest.Size(m)
}
func (m *GetNodeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeListRequest proto.InternalMessageInfo

type GetNodeListResponse struct {
	Nodes                []*common.Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetNodeListResponse) Reset()         { *m = GetNodeListResponse{} }
func (m *GetNodeListResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeListResponse) ProtoMessage()    {}
func (*GetNodeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{4}
}

func (m *GetNodeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeListResponse.Unmarshal(m, b)
}
func (m *GetNodeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeListResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeListResponse.Merge(m, src)
}
func (m *GetNodeListResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeListResponse.Size(m)
}
func (m *GetNodeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeListResponse proto.InternalMessageInfo

func (m *GetNodeListResponse) GetNodes() []*common.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// CreateContainer
type CreateContainerRequest struct {
	NodeId               string            `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ImageName            string            `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ContainerName        string            `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Volumes              map[string]string `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Envs                 []string          `protobuf:"bytes,6,rep,name=envs,proto3" json:"envs,omitempty"`
	Ports                map[int32]string  `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AutoPort             bool              `protobuf:"varint,8,opt,name=auto_port,json=autoPort,proto3" json:"auto_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateContainerRequest) Reset()         { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()    {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{5}
}

func (m *CreateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerRequest.Unmarshal(m, b)
}
func (m *CreateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerRequest.Marshal(b, m, deterministic)
}
func (m *CreateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerRequest.Merge(m, src)
}
func (m *CreateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContainerRequest.Size(m)
}
func (m *CreateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerRequest proto.InternalMessageInfo

func (m *CreateContainerRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *CreateContainerRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *CreateContainerRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *CreateContainerRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CreateContainerRequest) GetVolumes() map[string]string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *CreateContainerRequest) GetEnvs() []string {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *CreateContainerRequest) GetPorts() map[int32]string {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *CreateContainerRequest) GetAutoPort() bool {
	if m != nil {
		return m.AutoPort
	}
	return false
}

type CreateContainerResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Warnings             []string `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerResponse) Reset()         { *m = CreateContainerResponse{} }
func (m *CreateContainerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContainerResponse) ProtoMessage()    {}
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{6}
}

func (m *CreateContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerResponse.Unmarshal(m, b)
}
func (m *CreateContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerResponse.Marshal(b, m, deterministic)
}
func (m *CreateContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerResponse.Merge(m, src)
}
func (m *CreateContainerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContainerResponse.Size(m)
}
func (m *CreateContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerResponse proto.InternalMessageInfo

func (m *CreateContainerResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateContainerResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

// GetNode
type GetNodeRequest struct {
	NodeAddress          string   `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{7}
}

func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(m, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

type GetNodeResponse struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAlias            string   `protobuf:"bytes,2,opt,name=node_alias,json=nodeAlias,proto3" json:"node_alias,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeResponse) Reset()         { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()    {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{8}
}

func (m *GetNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeResponse.Unmarshal(m, b)
}
func (m *GetNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeResponse.Merge(m, src)
}
func (m *GetNodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeResponse.Size(m)
}
func (m *GetNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeResponse proto.InternalMessageInfo

func (m *GetNodeResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *GetNodeResponse) GetNodeAlias() string {
	if m != nil {
		return m.NodeAlias
	}
	return ""
}

func (m *GetNodeResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GetNodeResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// StartContainer
type StartContainerRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartContainerRequest) Reset()         { *m = StartContainerRequest{} }
func (m *StartContainerRequest) String() string { return proto.CompactTextString(m) }
func (*StartContainerRequest) ProtoMessage()    {}
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{9}
}

func (m *StartContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartContainerRequest.Unmarshal(m, b)
}
func (m *StartContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartContainerRequest.Marshal(b, m, deterministic)
}
func (m *StartContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartContainerRequest.Merge(m, src)
}
func (m *StartContainerRequest) XXX_Size() int {
	return xxx_messageInfo_StartContainerRequest.Size(m)
}
func (m *StartContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartContainerRequest proto.InternalMessageInfo

func (m *StartContainerRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *StartContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

// StopContainer
type StopContainerRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopContainerRequest) Reset()         { *m = StopContainerRequest{} }
func (m *StopContainerRequest) String() string { return proto.CompactTextString(m) }
func (*StopContainerRequest) ProtoMessage()    {}
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{10}
}

func (m *StopContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopContainerRequest.Unmarshal(m, b)
}
func (m *StopContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopContainerRequest.Marshal(b, m, deterministic)
}
func (m *StopContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopContainerRequest.Merge(m, src)
}
func (m *StopContainerRequest) XXX_Size() int {
	return xxx_messageInfo_StopContainerRequest.Size(m)
}
func (m *StopContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopContainerRequest proto.InternalMessageInfo

func (m *StopContainerRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *StopContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

// DeleteContainer
type DeleteContainerRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContainerRequest) Reset()         { *m = DeleteContainerRequest{} }
func (m *DeleteContainerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContainerRequest) ProtoMessage()    {}
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{11}
}

func (m *DeleteContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContainerRequest.Unmarshal(m, b)
}
func (m *DeleteContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContainerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContainerRequest.Merge(m, src)
}
func (m *DeleteContainerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContainerRequest.Size(m)
}
func (m *DeleteContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContainerRequest proto.InternalMessageInfo

func (m *DeleteContainerRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DeleteContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type System struct {
	Config               *Config      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	State                GomlapiState `protobuf:"varint,2,opt,name=state,proto3,enum=proto.gomlapi.GomlapiState" json:"state,omitempty"`
	Logs                 []string     `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *System) Reset()         { *m = System{} }
func (m *System) String() string { return proto.CompactTextString(m) }
func (*System) ProtoMessage()    {}
func (*System) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{12}
}

func (m *System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_System.Unmarshal(m, b)
}
func (m *System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_System.Marshal(b, m, deterministic)
}
func (m *System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_System.Merge(m, src)
}
func (m *System) XXX_Size() int {
	return xxx_messageInfo_System.Size(m)
}
func (m *System) XXX_DiscardUnknown() {
	xxx_messageInfo_System.DiscardUnknown(m)
}

var xxx_messageInfo_System proto.InternalMessageInfo

func (m *System) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *System) GetState() GomlapiState {
	if m != nil {
		return m.State
	}
	return GomlapiState_IDLE
}

func (m *System) GetLogs() []string {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Config struct {
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Nodes                []*common.NodeSummary  `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Images               []string               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	ImageInspects        []*common.ImageInspect `protobuf:"bytes,4,rep,name=image_inspects,json=imageInspects,proto3" json:"image_inspects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81150fdc90ded4c, []int{13}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Config) GetNodes() []*common.NodeSummary {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Config) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Config) GetImageInspects() []*common.ImageInspect {
	if m != nil {
		return m.ImageInspects
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.gomlapi.GomlapiState", GomlapiState_name, GomlapiState_value)
	proto.RegisterType((*SetConfigRequest)(nil), "proto.gomlapi.SetConfigRequest")
	proto.RegisterType((*GetSystemRequest)(nil), "proto.gomlapi.GetSystemRequest")
	proto.RegisterType((*GetSystemResponse)(nil), "proto.gomlapi.GetSystemResponse")
	proto.RegisterType((*GetNodeListRequest)(nil), "proto.gomlapi.GetNodeListRequest")
	proto.RegisterType((*GetNodeListResponse)(nil), "proto.gomlapi.GetNodeListResponse")
	proto.RegisterType((*CreateContainerRequest)(nil), "proto.gomlapi.CreateContainerRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.gomlapi.CreateContainerRequest.LabelsEntry")
	proto.RegisterMapType((map[int32]string)(nil), "proto.gomlapi.CreateContainerRequest.PortsEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.gomlapi.CreateContainerRequest.VolumesEntry")
	proto.RegisterType((*CreateContainerResponse)(nil), "proto.gomlapi.CreateContainerResponse")
	proto.RegisterType((*GetNodeRequest)(nil), "proto.gomlapi.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "proto.gomlapi.GetNodeResponse")
	proto.RegisterType((*StartContainerRequest)(nil), "proto.gomlapi.StartContainerRequest")
	proto.RegisterType((*StopContainerRequest)(nil), "proto.gomlapi.StopContainerRequest")
	proto.RegisterType((*DeleteContainerRequest)(nil), "proto.gomlapi.DeleteContainerRequest")
	proto.RegisterType((*System)(nil), "proto.gomlapi.System")
	proto.RegisterType((*Config)(nil), "proto.gomlapi.Config")
}

func init() {
	proto.RegisterFile("proto/v1/gomlapi/gomlapi-common.proto", fileDescriptor_a81150fdc90ded4c)
}

var fileDescriptor_a81150fdc90ded4c = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5f, 0x8f, 0xda, 0x46,
	0x10, 0x2f, 0xff, 0x0c, 0x0c, 0x7f, 0x4a, 0xb6, 0x17, 0xe2, 0x92, 0x54, 0x22, 0x96, 0xa2, 0xd2,
	0xaa, 0x40, 0x8f, 0xbc, 0xa4, 0x79, 0xa9, 0xc8, 0x85, 0x20, 0x4b, 0x2e, 0x8a, 0x4c, 0xae, 0x0f,
	0xf7, 0x82, 0xf6, 0xf0, 0xd6, 0x67, 0x9d, 0xbd, 0x4b, 0xbd, 0x0b, 0xa7, 0x7b, 0x69, 0x3f, 0x51,
	0xbf, 0x40, 0x3f, 0x5d, 0xb5, 0x7f, 0xcc, 0x01, 0xd7, 0x6b, 0x39, 0x29, 0x2f, 0xac, 0xe7, 0x37,
	0xbf, 0xf9, 0x79, 0x66, 0x99, 0x19, 0xc3, 0xab, 0x55, 0xca, 0x04, 0x1b, 0x6e, 0x4e, 0x87, 0x21,
	0x4b, 0x62, 0xbc, 0x8a, 0xb2, 0xb3, 0xbf, 0x64, 0x49, 0xc2, 0xe8, 0x40, 0xf9, 0x51, 0x43, 0x1d,
	0x03, 0xe3, 0xeb, 0xbc, 0xd8, 0x46, 0x69, 0xd6, 0x30, 0x60, 0xcb, 0x6b, 0x92, 0x6a, 0x72, 0xa7,
	0x73, 0xe8, 0xa5, 0x2c, 0x20, 0xc6, 0xf7, 0x22, 0x64, 0x2c, 0x8c, 0xc9, 0x50, 0xbe, 0x09, 0x53,
	0xca, 0x04, 0x16, 0x11, 0xa3, 0xdc, 0x78, 0x7f, 0x50, 0xc7, 0xb2, 0x1f, 0x12, 0xda, 0xe7, 0x37,
	0x38, 0x0c, 0x49, 0x3a, 0x64, 0x2b, 0xc5, 0xb8, 0xcf, 0x76, 0xc6, 0xd0, 0x9a, 0x13, 0x71, 0xc6,
	0xe8, 0x6f, 0x51, 0xe8, 0x93, 0xdf, 0xd7, 0x84, 0x0b, 0xd4, 0x07, 0x6b, 0xa9, 0x00, 0x3b, 0xd7,
	0xcd, 0xf5, 0x6a, 0xa3, 0xa7, 0x83, 0xbd, 0xcc, 0x07, 0x86, 0x6d, 0x48, 0x0e, 0x82, 0xd6, 0x94,
	0x88, 0xf9, 0x2d, 0x17, 0x24, 0x31, 0x12, 0xce, 0x3b, 0x78, 0xb2, 0x83, 0xf1, 0x15, 0xa3, 0x9c,
	0x48, 0x5d, 0xae, 0x90, 0x07, 0x74, 0x0d, 0xdd, 0x90, 0x9c, 0x13, 0x40, 0x53, 0x22, 0x66, 0x2c,
	0x20, 0x5e, 0xc4, 0x45, 0xa6, 0xfc, 0x33, 0x7c, 0xb5, 0x87, 0x1a, 0xed, 0x1e, 0x94, 0xe4, 0x0d,
	0x71, 0x3b, 0xd7, 0x2d, 0xf4, 0x6a, 0x23, 0x64, 0xa4, 0xcd, 0x1f, 0x20, 0xe9, 0xbe, 0x26, 0x38,
	0x7f, 0x17, 0xa1, 0x7d, 0x96, 0x12, 0x2c, 0xc8, 0x19, 0xa3, 0x02, 0x47, 0x94, 0xa4, 0x59, 0xe1,
	0xcf, 0xa0, 0x2c, 0x39, 0x8b, 0x28, 0x50, 0x19, 0x56, 0x7d, 0x4b, 0x9a, 0x6e, 0x80, 0xbe, 0x01,
	0x88, 0x12, 0x1c, 0x92, 0x05, 0xc5, 0x09, 0xb1, 0xf3, 0xca, 0x57, 0x55, 0xc8, 0x0c, 0x27, 0x04,
	0xbd, 0x82, 0xe6, 0x32, 0xd3, 0xd2, 0x94, 0x82, 0xa2, 0x34, 0xb6, 0xa8, 0xa2, 0xb9, 0x60, 0xc5,
	0xf8, 0x92, 0xc4, 0xdc, 0x2e, 0xaa, 0x24, 0x4f, 0x0f, 0xef, 0xf5, 0x5f, 0xb3, 0x1a, 0x78, 0x2a,
	0x66, 0x42, 0x45, 0x7a, 0xeb, 0x1b, 0x01, 0xe4, 0x41, 0x79, 0xc3, 0xe2, 0x75, 0x42, 0xb8, 0x5d,
	0x52, 0x5a, 0xa3, 0xe3, 0xb4, 0x7e, 0xd5, 0x41, 0x5a, 0x2c, 0x93, 0x40, 0x08, 0x8a, 0x84, 0x6e,
	0xb8, 0x6d, 0x75, 0x0b, 0xbd, 0xaa, 0xaf, 0x9e, 0xd1, 0x07, 0x28, 0xad, 0x58, 0x2a, 0xb8, 0x5d,
	0x56, 0xfa, 0x3f, 0x1e, 0xa7, 0xff, 0x51, 0x86, 0x68, 0x75, 0x1d, 0x8e, 0x9e, 0x43, 0x15, 0xaf,
	0x05, 0x5b, 0x48, 0xcb, 0xae, 0x74, 0x73, 0xbd, 0x8a, 0x5f, 0x91, 0x80, 0x64, 0x76, 0x7e, 0x82,
	0xda, 0x4e, 0x75, 0xa8, 0x05, 0x85, 0x6b, 0x72, 0x6b, 0xee, 0x5e, 0x3e, 0xa2, 0x13, 0x28, 0x6d,
	0x70, 0xbc, 0xce, 0xee, 0x5c, 0x1b, 0x6f, 0xf3, 0x6f, 0x72, 0x9d, 0xb7, 0x50, 0xdf, 0x2d, 0xe6,
	0x51, 0xb1, 0x6f, 0x00, 0xee, 0x12, 0xdd, 0x8d, 0x2c, 0xfd, 0x4f, 0xa4, 0x33, 0x81, 0x67, 0xf7,
	0x2a, 0x37, 0x1d, 0xd8, 0x84, 0xfc, 0xb6, 0x6f, 0xf2, 0x51, 0x80, 0x3a, 0x50, 0xb9, 0xc1, 0x29,
	0x8d, 0x68, 0xc8, 0xed, 0xbc, 0xba, 0xd8, 0xad, 0xed, 0xbc, 0x86, 0xa6, 0x69, 0xe2, 0xac, 0xf5,
	0x5e, 0x42, 0x5d, 0xb5, 0x1e, 0x0e, 0x82, 0x94, 0x70, 0x6e, 0x74, 0x6a, 0x12, 0x1b, 0x6b, 0xc8,
	0xf9, 0x13, 0xbe, 0xdc, 0x06, 0x99, 0x77, 0xfe, 0x57, 0xc3, 0x6a, 0xb9, 0x38, 0xc2, 0x3c, 0x6b,
	0x58, 0x25, 0x26, 0x01, 0x99, 0xdb, 0x15, 0xe3, 0x62, 0xa7, 0x55, 0xb7, 0x36, 0xb2, 0xa1, 0x9c,
	0x25, 0x51, 0x54, 0xae, 0xcc, 0x74, 0xe6, 0xf0, 0x74, 0x2e, 0x70, 0x2a, 0x8e, 0x9f, 0x9b, 0x97,
	0x50, 0xbf, 0x1b, 0x8c, 0x28, 0x30, 0x89, 0xd4, 0xb6, 0x98, 0x1b, 0x38, 0x3e, 0x9c, 0xcc, 0x05,
	0x5b, 0x7d, 0x56, 0xcd, 0x4f, 0xd0, 0x7e, 0x4f, 0x62, 0xf2, 0x98, 0x09, 0x3f, 0x42, 0xf5, 0x0f,
	0xb0, 0xf4, 0x86, 0x7a, 0xe4, 0x82, 0x44, 0xa7, 0x50, 0xe2, 0x02, 0x0b, 0xdd, 0x4e, 0xcd, 0xd1,
	0xf3, 0x03, 0xf6, 0x54, 0x9f, 0x73, 0x49, 0xf1, 0x35, 0x53, 0x4e, 0x64, 0xcc, 0x42, 0x6e, 0x17,
	0xf4, 0x44, 0xca, 0x67, 0xe7, 0xaf, 0x1c, 0x58, 0x5a, 0xf9, 0xe1, 0x32, 0x86, 0xd9, 0x1a, 0xcc,
	0xab, 0xa9, 0xfd, 0xfa, 0xfe, 0x1a, 0x9c, 0xaf, 0x93, 0x04, 0xcb, 0xf1, 0x54, 0x3c, 0xd4, 0x06,
	0x4b, 0xed, 0xb1, 0xec, 0x55, 0xc6, 0x42, 0x63, 0x68, 0xea, 0x8d, 0x17, 0x51, 0xbe, 0x22, 0x4b,
	0x91, 0xed, 0xac, 0xce, 0xbe, 0xa2, 0x2b, 0x39, 0xae, 0xa6, 0xf8, 0x8d, 0x68, 0xc7, 0xe2, 0xdf,
	0x9f, 0x43, 0x7d, 0xb7, 0x34, 0x54, 0x81, 0xa2, 0xfb, 0xde, 0x9b, 0xb4, 0xbe, 0x40, 0x2d, 0xa8,
	0xbb, 0x33, 0xf7, 0x93, 0x3b, 0xf6, 0xdc, 0x0b, 0x77, 0x36, 0x6d, 0xe5, 0xd0, 0x13, 0x68, 0xb8,
	0xbf, 0x8c, 0xa7, 0x93, 0xc5, 0xc7, 0x73, 0xcf, 0x93, 0x50, 0x1e, 0xb5, 0x01, 0xed, 0x41, 0x8b,
	0x0f, 0x63, 0xd7, 0x6b, 0x15, 0xde, 0x7d, 0x77, 0xf1, 0x6d, 0x18, 0x89, 0xab, 0xf5, 0xa5, 0xcc,
	0x41, 0x7d, 0x69, 0xd5, 0x0f, 0x11, 0xc3, 0xc3, 0xcf, 0xf0, 0xa5, 0xa5, 0x90, 0xd7, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x1e, 0x3d, 0x6f, 0x51, 0xa1, 0x07, 0x00, 0x00,
}
