// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/common/node.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeSummary struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias                string   `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Hostname             string   `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeSummary) Reset()         { *m = NodeSummary{} }
func (m *NodeSummary) String() string { return proto.CompactTextString(m) }
func (*NodeSummary) ProtoMessage()    {}
func (*NodeSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7e35087e4b4050, []int{0}
}

func (m *NodeSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSummary.Unmarshal(m, b)
}
func (m *NodeSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSummary.Marshal(b, m, deterministic)
}
func (m *NodeSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSummary.Merge(m, src)
}
func (m *NodeSummary) XXX_Size() int {
	return xxx_messageInfo_NodeSummary.Size(m)
}
func (m *NodeSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSummary.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSummary proto.InternalMessageInfo

func (m *NodeSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeSummary) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *NodeSummary) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NodeSummary) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type Node struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias                string       `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Hostname             string       `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address              string       `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int32        `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	GpuStatuses          []*GPUStatus `protobuf:"bytes,6,rep,name=gpu_statuses,json=gpuStatuses,proto3" json:"gpu_statuses,omitempty"`
	Containers           []*Container `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7e35087e4b4050, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Node) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetGpuStatuses() []*GPUStatus {
	if m != nil {
		return m.GpuStatuses
	}
	return nil
}

func (m *Node) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type GPUStatus struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	MemoryTotalSize      uint64   `protobuf:"varint,2,opt,name=memory_total_size,json=memoryTotalSize,proto3" json:"memory_total_size,omitempty"`
	MemoryUsedSize       uint64   `protobuf:"varint,3,opt,name=memory_used_size,json=memoryUsedSize,proto3" json:"memory_used_size,omitempty"`
	Temperature          uint32   `protobuf:"varint,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPUStatus) Reset()         { *m = GPUStatus{} }
func (m *GPUStatus) String() string { return proto.CompactTextString(m) }
func (*GPUStatus) ProtoMessage()    {}
func (*GPUStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7e35087e4b4050, []int{2}
}

func (m *GPUStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUStatus.Unmarshal(m, b)
}
func (m *GPUStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUStatus.Marshal(b, m, deterministic)
}
func (m *GPUStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUStatus.Merge(m, src)
}
func (m *GPUStatus) XXX_Size() int {
	return xxx_messageInfo_GPUStatus.Size(m)
}
func (m *GPUStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GPUStatus proto.InternalMessageInfo

func (m *GPUStatus) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GPUStatus) GetMemoryTotalSize() uint64 {
	if m != nil {
		return m.MemoryTotalSize
	}
	return 0
}

func (m *GPUStatus) GetMemoryUsedSize() uint64 {
	if m != nil {
		return m.MemoryUsedSize
	}
	return 0
}

func (m *GPUStatus) GetTemperature() uint32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func init() {
	proto.RegisterType((*NodeSummary)(nil), "proto.common.NodeSummary")
	proto.RegisterType((*Node)(nil), "proto.common.Node")
	proto.RegisterType((*GPUStatus)(nil), "proto.common.GPUStatus")
}

func init() { proto.RegisterFile("proto/v1/common/node.proto", fileDescriptor_ec7e35087e4b4050) }

var fileDescriptor_ec7e35087e4b4050 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x95, 0xdd, 0x6c, 0x4b, 0x9d, 0xb6, 0x80, 0x85, 0x44, 0x14, 0xf5, 0xb0, 0xda, 0x03,
	0x8a, 0x10, 0x8d, 0x05, 0x1c, 0x90, 0x38, 0xc2, 0x81, 0x1b, 0x42, 0x09, 0xbd, 0x70, 0x59, 0xb9,
	0xf1, 0xc8, 0xb5, 0x88, 0x3d, 0x91, 0xed, 0x00, 0xed, 0x9b, 0xf0, 0x8c, 0xbc, 0x04, 0xca, 0x64,
	0x5b, 0x85, 0x05, 0xa1, 0x5e, 0xe2, 0xfc, 0xff, 0xff, 0x65, 0x26, 0x33, 0x32, 0x2b, 0x7a, 0x8f,
	0x11, 0xc5, 0xb7, 0x97, 0xa2, 0x45, 0x6b, 0xd1, 0x09, 0x87, 0x0a, 0x2a, 0x32, 0xf9, 0x31, 0x1d,
	0xd5, 0x14, 0x14, 0x67, 0xfb, 0xa4, 0xc2, 0xf6, 0x2b, 0xf8, 0x89, 0x2d, 0xce, 0x34, 0xa2, 0xee,
	0x40, 0xc8, 0xde, 0x08, 0xe9, 0x1c, 0x46, 0x19, 0x0d, 0xba, 0xb0, 0x4b, 0x5f, 0xd0, 0xd1, 0x9e,
	0x6b, 0x70, 0xe7, 0xe1, 0xbb, 0xd4, 0x1a, 0xbc, 0xc0, 0x9e, 0x88, 0xbf, 0xe9, 0x8d, 0x61, 0xd9,
	0x47, 0x54, 0xd0, 0x0c, 0xd6, 0x4a, 0x7f, 0xcd, 0x4f, 0xd9, 0xc2, 0xa8, 0x3c, 0x59, 0x27, 0xe5,
	0x51, 0xbd, 0x30, 0x8a, 0x3f, 0x61, 0x2b, 0xd9, 0x19, 0x19, 0xf2, 0x05, 0x59, 0x93, 0xe0, 0x39,
	0x3b, 0x94, 0x4a, 0x79, 0x08, 0x21, 0x4f, 0xc9, 0xbf, 0x95, 0xbc, 0x60, 0x0f, 0xae, 0x30, 0x44,
	0x27, 0x2d, 0xe4, 0x2b, 0x8a, 0xee, 0xf4, 0xe6, 0x57, 0xc2, 0xd2, 0xb1, 0xd7, 0x3d, 0x9b, 0xcc,
	0x4b, 0x2d, 0xff, 0x2c, 0xf5, 0x9f, 0x1f, 0xe0, 0x2c, 0xed, 0xd1, 0x47, 0x6a, 0xbe, 0xaa, 0xe9,
	0x9d, 0xbf, 0x65, 0xc7, 0xba, 0x1f, 0xb6, 0x21, 0xca, 0x38, 0x04, 0x08, 0xf9, 0xc1, 0x7a, 0x59,
	0x66, 0xaf, 0x9e, 0x56, 0xf3, 0x95, 0x57, 0x1f, 0x3e, 0x5d, 0x34, 0x04, 0xd4, 0x99, 0xee, 0x87,
	0x66, 0xc7, 0xf2, 0x37, 0x8c, 0xb5, 0xe8, 0xa2, 0x34, 0x0e, 0x7c, 0xc8, 0x0f, 0xff, 0xf5, 0xe5,
	0xfb, 0xdb, 0xbc, 0x9e, 0xa1, 0x9b, 0x9f, 0x09, 0x3b, 0xba, 0xab, 0x39, 0x8e, 0x68, 0x9c, 0x82,
	0x1f, 0x34, 0xf5, 0x49, 0x3d, 0x09, 0xfe, 0x9c, 0x3d, 0xb6, 0x60, 0xd1, 0x5f, 0x6f, 0x23, 0x46,
	0xd9, 0x6d, 0x83, 0xb9, 0x01, 0x5a, 0x42, 0x5a, 0x3f, 0x9c, 0x82, 0xcf, 0xa3, 0xdf, 0x98, 0x1b,
	0xe0, 0x25, 0x7b, 0xb4, 0x63, 0x87, 0x00, 0x6a, 0x42, 0x97, 0x84, 0x9e, 0x4e, 0xfe, 0x45, 0x00,
	0x45, 0xe4, 0x9a, 0x65, 0x11, 0x6c, 0x0f, 0x5e, 0xc6, 0xc1, 0x03, 0x2d, 0xe8, 0xa4, 0x9e, 0x5b,
	0xef, 0xca, 0x2f, 0xcf, 0xb4, 0x89, 0x57, 0xc3, 0xe5, 0x38, 0x82, 0xd0, 0x68, 0x3b, 0x7a, 0x40,
	0x14, 0x7b, 0xf7, 0xee, 0xf2, 0x80, 0x8c, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x6e,
	0x32, 0xe4, 0xbb, 0x02, 0x00, 0x00,
}
