// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/auth/auth-common.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NewUser
type NewUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role                 int32    `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3f7a3dd26927bfe, []int{0}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NewUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserRequest) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

type NewUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserResponse) Reset()         { *m = NewUserResponse{} }
func (m *NewUserResponse) String() string { return proto.CompactTextString(m) }
func (*NewUserResponse) ProtoMessage()    {}
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3f7a3dd26927bfe, []int{1}
}

func (m *NewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserResponse.Unmarshal(m, b)
}
func (m *NewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserResponse.Marshal(b, m, deterministic)
}
func (m *NewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserResponse.Merge(m, src)
}
func (m *NewUserResponse) XXX_Size() int {
	return xxx_messageInfo_NewUserResponse.Size(m)
}
func (m *NewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserResponse proto.InternalMessageInfo

// Login
type LoginRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3f7a3dd26927bfe, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3f7a3dd26927bfe, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUserRequest)(nil), "proto.auth.NewUserRequest")
	proto.RegisterType((*NewUserResponse)(nil), "proto.auth.NewUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "proto.auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.auth.LoginResponse")
}

func init() { proto.RegisterFile("proto/v1/auth/auth-common.proto", fileDescriptor_a3f7a3dd26927bfe) }

var fileDescriptor_a3f7a3dd26927bfe = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0x4f, 0x4b, 0xf4, 0x30,
	0x10, 0xc6, 0xe9, 0xfb, 0xee, 0xae, 0x3a, 0xf8, 0x07, 0x83, 0x60, 0x29, 0x82, 0x4b, 0x51, 0xd9,
	0x83, 0x6d, 0x10, 0xbf, 0x81, 0x9e, 0x04, 0xf1, 0x50, 0xf0, 0xe2, 0x45, 0xb2, 0xed, 0x90, 0x2d,
	0x36, 0x99, 0x98, 0xa4, 0xf6, 0xeb, 0x4b, 0xa7, 0xcb, 0x82, 0x78, 0xf4, 0x32, 0x33, 0xbf, 0x79,
	0x1e, 0x9e, 0x81, 0x81, 0x4b, 0xe7, 0x29, 0x92, 0xfc, 0xba, 0x93, 0xaa, 0x8f, 0x1b, 0x2e, 0x45,
	0x4d, 0xc6, 0x90, 0x2d, 0x59, 0x11, 0xc0, 0xad, 0x1c, 0x85, 0xec, 0x42, 0x13, 0xe9, 0x0e, 0xa5,
	0x72, 0xad, 0x54, 0xd6, 0x52, 0x54, 0xb1, 0x25, 0x1b, 0x26, 0x67, 0x76, 0xcb, 0xad, 0x2e, 0x34,
	0xda, 0x22, 0x0c, 0x4a, 0x6b, 0xf4, 0x92, 0x1c, 0x3b, 0x7e, 0xbb, 0x73, 0x03, 0xc7, 0x2f, 0x38,
	0xbc, 0x06, 0xf4, 0x15, 0x7e, 0xf6, 0x18, 0xa2, 0x38, 0x87, 0xbd, 0x3e, 0xa0, 0x7f, 0x6f, 0x9b,
	0x34, 0x59, 0x26, 0xab, 0x83, 0x6a, 0x31, 0xe2, 0x53, 0x23, 0x32, 0xd8, 0x77, 0x2a, 0x84, 0x81,
	0x7c, 0x93, 0xfe, 0x63, 0x65, 0xc7, 0x42, 0xc0, 0xcc, 0x2a, 0x83, 0xe9, 0x7f, 0xde, 0xf3, 0x3c,
	0xee, 0x3c, 0x75, 0x98, 0xce, 0x96, 0xc9, 0x6a, 0x5e, 0xf1, 0x9c, 0x9f, 0xc2, 0xc9, 0xee, 0x5c,
	0x70, 0x64, 0x03, 0xe6, 0x8f, 0x70, 0xf8, 0x4c, 0xba, 0xb5, 0x7f, 0xb9, 0x9f, 0x5f, 0xc3, 0xd1,
	0x36, 0x64, 0x4a, 0x15, 0x67, 0x30, 0x8f, 0xf4, 0x81, 0x76, 0x9b, 0x31, 0xc1, 0xc3, 0xcd, 0xdb,
	0x95, 0x6e, 0xe3, 0xa6, 0x5f, 0x97, 0x35, 0x19, 0xa9, 0xc9, 0x74, 0x5c, 0x30, 0xca, 0x1f, 0xff,
	0x5f, 0x2f, 0x18, 0xef, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xe2, 0x06, 0x16, 0x97, 0x01,
	0x00, 0x00,
}
